/*

Implement an autocomplete system. That is, given a query string s and a set of all
possible query strings, return all strings in the set that have s as a prefix.

For example, given the query string de and the set of strings [dog, deer, deal],
return [deer, deal].

Hint: Try preprocessing the dictionary into a more efficient data structure to
speed up queries.

*/

const words: string[] = [ "aback", "abaft", "abandoned", "abashed", "aberrant",
"ablaze", "able", "abnormal", "aboard", "aboriginal", "abortive", "abounding",
"abrasive", "abrupt", "absent", "absorbed", "absorbing", "abstracted", "absurd",
"abundant", "abusive", "accept", "acceptable", "accessible", "accidental", "account",
"accurate", "achiever", "acid", "acidic", "acoustic", "acoustics", "acrid", "act",
"action", "activity", "actor", "actually", "ad hoc", "adamant", "adaptable", "add",
"addicted", "addition", "adhesive", "adjoining", "adjustment", "admire", "admit",
"adorable", "adventurous", "advertisement", "advice", "advise", "afford", "afraid",
"aftermath", "afternoon", "afterthought", "aggressive", "agonizing", "agree",
"agreeable", "agreement", "ahead", "air", "airplane", "airport", "ajar", "alarm",
"alcoholic", "alert", "alert", "alike", "alive", "alleged", "allow", "alluring", "aloof",
"amazing", "ambiguous", "ambitious", "amount", "amuck", "amuse", "amused", "amusement",
"amusing", "analyse", "ancient", "anger", "angle", "angry", "animal", "animated",
"announce", "annoy", "annoyed", "annoying", "answer", "ants", "anxious", "apathetic",
"apologise", "apparatus", "apparel", "appear", "applaud", "appliance", "appreciate",
"approval", "approve", "aquatic", "arch", "argue", "argument", "arithmetic", "arm",
"army", "aromatic", "arrange", "arrest", "arrive", "arrogant", "art", "ashamed", "ask",
"aspiring", "assorted", "astonishing", "attach", "attack", "attack", "attempt", "attend",
"attract", "attraction", "attractive", "aunt", "auspicious", "authority", "automatic",
"available", "average", "avoid", "awake", "aware", "awesome", "awful", "axiomatic",
"babies", "baby", "back", "back", "bad", "badge", "bag", "bait", "bake", "balance",
"balance", "ball", "ban", "bang", "barbarous", "bare", "base", "baseball", "bashful",
"basin", "basket", "basketball", "bat", "bat", "bath", "bathe", "battle", "battle",
"bawdy", "bead", "beam", "bear", "beautiful", "bed", "bedroom", "beds", "bee", "beef",
"befitting", "beg", "beginner", "behave", "behavior", "belief", "believe", "bell",
"belligerent", "bells", "belong", "beneficial", "bent", "berry", "berserk", "best",
"better", "bewildered", "big", "bike", "bikes", "billowy", "bird", "birds", "birth",
"birthday", "bit", "bite", "bite-sized", "bitter", "bizarre", "black", "black-and-white",
"blade", "bleach", "bless", "blind", "blink", "blood", "bloody", "blot", "blow", "blue",
"blue-eyed", "blush", "blushing", "board", "boast", "boat", "boil", "boiling", "bolt",
"bomb", "bomb", "bone", "book", "book", "books", "boorish", "boot", "border", "bore",
"bored", "boring", "borrow", "bottle", "bounce", "bouncy", "boundary", "boundless",
"bow", "box", "box", "boy", "brainy", "brake", "brake", "branch", "branch", "brash",
"brass", "brave", "brawny", "breakable", "breath", "breathe", "breezy", "brick",
"bridge", "brief", "bright", "bright", "broad", "broken", "brother", "brown", "bruise",
"brush", "bubble", "bubble", "bucket", "building", "bulb", "bump", "bumpy", "burly",
"burn", "burst", "bury", "bushes", "business", "bustling", "busy", "butter", "button",
"buzz", "cabbage", "cable", "cactus", "cagey", "cake", "cakes", "calculate",
"calculating", "calculator", "calendar", "call", "callous", "calm", "camera", "camp",
"camp", "can", "cannon", "canvas", "cap", "capable", "capricious", "caption", "car",
"card", "care", "care", "careful", "careless", "caring", "carpenter", "carriage",
"carry", "cars", "cart", "carve", "cast", "cat", "cats", "cattle", "cause", "cause",
"cautious", "cave", "ceaseless", "celery", "cellar", "cemetery", "cent", "certain",
"chalk", "challenge", "chance", "change", "change", "changeable", "channel", "charge",
"charming", "chase", "cheap", "cheat", "check", "cheer", "cheerful", "cheese",
"chemical", "cherries", "cherry", "chess", "chew", "chicken", "chickens", "chief",
"childlike", "children", "chilly", "chin", "chivalrous", "choke", "chop", "chubby",
"chunky", "church", "circle", "claim", "clam", "clammy", "clap", "class", "classy",
"clean", "clean", "clear", "clear", "clever", "clip", "cloistered", "close", "closed",
"cloth", "cloudy", "clover", "club", "clumsy", "cluttered", "coach", "coach", "coal",
"coast", "coat", "cobweb", "coherent", "coil", "coil", "cold", "collar", "collect",
"color", "colorful", "colossal", "colour", "comb", "combative", "comfortable", "command",
"committee", "common", "communicate", "company", "compare", "comparison", "compete",
"competition", "complain", "complete", "complete", "complex", "concentrate", "concern",
"concerned", "condemned", "condition", "confess", "confuse", "confused", "connect",
"connection", "conscious", "consider", "consist", "contain", "continue", "control",
"cooing", "cook", "cool", "cooperative", "coordinated", "copper", "copy", "corn",
"correct", "cough", "cough", "count", "country", "courageous", "cover", "cover", "cow",
"cowardly", "cows", "crabby", "crack", "crack", "cracker", "crash", "crate", "craven",
"crawl", "crayon", "crazy", "cream", "creator", "creature", "credit", "creepy", "crib",
"crime", "crook", "crooked", "cross", "crow", "crowd", "crowded", "crown", "cruel",
"crush", "cry", "cub", "cuddly", "cultured", "cumbersome", "cup", "cure", "curious",
"curl", "curly", "current", "curtain", "curve", "curve", "curved", "curvy", "cushion",
"cut", "cute", "cute", "cycle", "cynical", "dad", "daffy", "daily", "dam", "damage",
"damaged", "damaging", "damp", "dance", "dangerous", "dapper", "dare", "dark", "dashing",
"daughter", "day", "dazzling", "dead", "deadpan", "deafening", "dear", "death",
"debonair", "debt", "decay", "deceive", "decide", "decision", "decisive", "decorate",
"decorous", "deep", "deeply", "deer", "defeated", "defective", "defiant", "degree",
"delay", "delicate", "delicious", "delight", "delightful", "delirious", "deliver",
"demonic", "depend", "dependent", "depressed", "deranged", "describe", "descriptive",
"desert", "deserted", "deserve", "design", "desire", "desk", "destroy", "destruction",
"detail", "detailed", "detect", "determined", "develop", "development", "devilish",
"didactic", "different", "difficult", "digestion", "diligent", "dime", "dinner",
"dinosaurs", "direction", "direful", "dirt", "dirty", "disagree", "disagreeable",
"disappear", "disapprove", "disarm", "disastrous", "discover", "discovery", "discreet",
"discussion", "disgusted", "disgusting", "disillusioned", "dislike", "dispensable",
"distance", "distinct", "distribution", "disturbed", "divergent", "divide", "division",
"dizzy", "dock", "doctor", "dog", "dogs", "doll", "dolls", "domineering", "donkey",
"door", "double", "doubt", "doubtful", "downtown", "drab", "draconian", "drag", "drain",
"drain", "dramatic", "drawer", "dream", "dreary", "dress", "dress", "drink", "drip",
"driving", "drop", "drop", "drown", "drum", "drunk", "dry", "dry", "duck", "ducks",
"dull", "dust", "dust", "dusty", "dusty", "dynamic", "dysfunctional", "eager", "ear",
"early", "earn", "earsplitting", "earth", "earthquake", "earthy", "easy", "eatable",
"economic", "edge", "educate", "educated", "education", "effect", "efficacious",
"efficient", "egg", "eggnog", "eggs", "eight", "elastic", "elated", "elbow", "elderly",
"electric", "elegant", "elfin", "elite", "embarrass", "embarrassed", "eminent", "employ",
"empty", "empty", "enchanted", "enchanting", "encourage", "encouraging", "end", "end",
"endurable", "energetic", "engine", "enjoy", "enormous", "enter", "entertain",
"entertaining", "enthusiastic", "envious", "equable", "equal", "erect", "erratic",
"error", "escape", "ethereal", "evanescent", "evasive", "even", "event", "examine",
"example", "excellent", "exchange", "excite", "excited", "exciting", "exclusive",
"excuse", "exercise", "exist", "existence", "exotic", "expand", "expansion", "expect",
"expensive", "experience", "expert", "explain", "explode", "extend", "extra-large",
"extra-small", "exuberant", "exultant", "eye", "eyes", "fabulous", "face", "face",
"fact", "fade", "faded", "fail", "faint", "fair", "fairies", "faithful", "fall",
"fallacious", "false", "familiar", "famous", "fanatical", "fancy", "fancy", "fang",
"fantastic", "far", "far-flung", "farm", "fascinated", "fast", "fasten", "fat", "faulty",
"fax", "fear", "fear", "fearful", "fearless", "feeble", "feeling", "feigned", "female",
"fence", "fertile", "festive", "fetch", "few", "field", "fierce", "file", "fill", "film",
"filthy", "fine", "finger", "finger", "finicky", "fire", "fire", "fireman", "first",
"fish", "fit", "five", "fix", "fixed", "flag", "flagrant", "flaky", "flame", "flap",
"flash", "flashy", "flat", "flavor", "flawless", "flesh", "flight", "flimsy", "flippant",
"float", "flock", "flood", "floor", "flow", "flower", "flower", "flowers", "flowery",
"fluffy", "fluttering", "fly", "foamy", "fog", "fold", "fold", "follow", "food", "fool",
"foolish", "foot", "force", "force", "foregoing", "forgetful", "fork", "form", "form",
"fortunate", "found", "four", "fowl", "fragile", "frail", "frame", "frame", "frantic",
"free", "freezing", "frequent", "fresh", "fretful", "friction", "friend", "friendly",
"friends", "frighten", "frightened", "frightening", "frog", "frogs", "front", "fruit",
"fry", "fuel", "full", "fumbling", "functional", "funny", "furniture", "furry",
"furtive", "future", "futuristic", "fuzzy", "gabby", "gainful", "gamy", "gaping",
"garrulous", "gate", "gather", "gaudy", "gaze", "geese", "general", "gentle", "ghost",
"giant", "giants", "giddy", "gifted", "gigantic", "giraffe", "girl", "girls",
"glamorous", "glass", "gleaming", "glib", "glistening", "glorious", "glossy", "glove",
"glow", "glue", "godly", "gold", "good", "goofy", "gorgeous", "government", "governor",
"grab", "graceful", "grade", "grain", "grandfather", "grandiose", "grandmother", "grape",
"grass", "grate", "grateful", "gratis", "gray", "grease", "greasy", "great", "greedy",
"green", "greet", "grey", "grieving", "grin", "grip", "grip", "groan", "groovy",
"grotesque", "grouchy", "ground", "group", "growth", "grubby", "gruesome", "grumpy",
"guarantee", "guard", "guarded", "guess", "guide", "guide", "guiltless", "guitar",
"gullible", "gun", "gusty", "guttural", "habitual", "hair", "haircut", "half", "hall",
"hallowed", "halting", "hammer", "hammer", "hand", "hand", "handle", "hands", "handsome",
"handsomely", "handy", "hang", "hanging", "hapless", "happen", "happy", "harass",
"harbor", "hard", "hard-to-find", "harm", "harmonious", "harmony", "harsh", "hat",
"hate", "hate", "hateful", "haunt", "head", "head", "heady", "heal", "health", "healthy",
"heap", "heartbreaking", "heat", "heat", "heavenly", "heavy", "hellish", "help",
"helpful", "helpless", "hesitant", "hideous", "high", "high-pitched", "highfalutin",
"hilarious", "hill", "hissing", "historical", "history", "hobbies", "hole", "holiday",
"holistic", "hollow", "home", "homeless", "homely", "honey", "honorable", "hook", "hook",
"hop", "hope", "hope", "horn", "horrible", "horse", "horses", "hose", "hospitable",
"hospital", "hot", "hot", "hour", "house", "houses", "hover", "hug", "huge", "hulking",
"hum", "humdrum", "humor", "humorous", "hungry", "hunt", "hurried", "hurry", "hurt",
"hushed", "husky", "hydrant", "hypnotic", "hysterical", "ice", "icicle", "icky", "icy",
"idea", "identify", "idiotic", "ignorant", "ignore", "ill", "ill-fated", "ill-informed",
"illegal", "illustrious", "imaginary", "imagine", "immense", "imminent", "impartial",
"imperfect", "impolite", "important", "imported", "impossible", "impress", "improve",
"impulse", "incandescent", "include", "income", "incompetent", "inconclusive",
"increase", "increase", "incredible", "industrious", "industry", "inexpensive",
"infamous", "influence", "inform", "inject", "injure", "ink", "innate", "innocent",
"inquisitive", "insect", "insidious", "instinctive", "instruct", "instrument",
"insurance", "intelligent", "intend", "interest", "interest", "interesting", "interfere",
"internal", "interrupt", "introduce", "invent", "invention", "invincible", "invite",
"irate", "iron", "irritate", "irritating", "island", "itch", "itchy", "jaded", "jagged",
"jail", "jail", "jam", "jam", "jar", "jazzy", "jealous", "jeans", "jelly", "jellyfish",
"jewel", "jittery", "jobless", "jog", "join", "join", "joke", "jolly", "joyous", "judge",
"judge", "judicious", "juggle", "juice", "juicy", "jumbled", "jump", "jump", "jumpy",
"juvenile", "kaput", "keen", "kettle", "key", "kick", "kick", "kill", "kind",
"kindhearted", "kindly", "kiss", "kiss", "kittens", "kitty", "knee", "kneel", "knife",
"knit", "knock", "knot", "knot", "knotty", "knowing", "knowledge", "knowledgeable",
"known", "label", "labored", "laborer", "lace", "lackadaisical", "lacking", "ladybug",
"lake", "lame", "lamentable", "lamp", "land", "land", "language", "languid", "large",
"last", "last", "late", "laugh", "laugh", "laughable", "launch", "lavish", "lazy",
"lean", "learn", "learned", "leather", "left", "leg", "legal", "legs", "lethal",
"letter", "letters", "lettuce", "level", "level", "level", "lewd", "library", "license",
"lick", "lie", "light", "lighten", "like", "like", "likeable", "limit", "limping",
"line", "linen", "lip", "liquid", "list", "listen", "literate", "little", "live",
"lively", "lively", "living", "load", "loaf", "lock", "lock", "locket", "lonely", "long",
"long", "long-term", "longing", "look", "look", "loose", "lopsided", "loss", "loud",
"loutish", "love", "love", "lovely", "loving", "low", "low", "lowly", "lucky",
"ludicrous", "lumber", "lumpy", "lunch", "lunchroom", "lush", "luxuriant", "lying",
"lyrical", "macabre", "machine", "macho", "maddening", "madly", "magenta", "magic",
"magical", "magnificent", "maid", "mailbox", "majestic", "makeshift", "male",
"malicious", "mammoth", "man", "man", "manage", "maniacal", "many", "marble", "march",
"mark", "mark", "marked", "market", "married", "marry", "marvelous", "mask", "mass",
"massive", "match", "match", "mate", "material", "materialistic", "matter", "mature",
"meal", "mean", "measly", "measure", "measure", "meat", "meaty", "meddle", "medical",
"meek", "meeting", "mellow", "melodic", "melt", "melted", "memorise", "memory", "men",
"mend", "merciful", "mere", "mess up", "messy", "metal", "mice", "middle", "mighty",
"military", "milk", "milk", "milky", "mind", "mindless", "mine", "mine", "miniature",
"minister", "minor", "mint", "minute", "miscreant", "miss", "mist", "misty", "mitten",
"mix", "mixed", "moan", "moaning", "modern", "moldy", "mom", "momentous", "money",
"monkey", "month", "moon", "moor", "morning", "mother", "motion", "motionless",
"mountain", "mountainous", "mourn", "mouth", "move", "move", "muddle", "muddled", "mug",
"multiply", "mundane", "murder", "murky", "muscle", "mushy", "mute", "mysterious",
"nail", "naive", "name", "name", "nappy", "narrow", "nasty", "nation", "natural",
"naughty", "nauseating", "near", "neat", "nebulous", "necessary", "neck", "need", "need",
"needle", "needless", "needy", "neighborly", "nerve", "nervous", "nest", "nest", "new",
"next", "nice", "nifty", "night", "nimble", "nine", "nippy", "nod", "noise", "noiseless",
"noisy", "nonchalant", "nondescript", "nonstop", "normal", "north", "nose", "nostalgic",
"nosy", "note", "note", "notebook", "notice", "noxious", "null", "number", "number",
"numberless", "numerous", "nut", "nutritious", "nutty", "oafish", "oatmeal", "obedient",
"obeisant", "obese", "obey", "object", "obnoxious", "obscene", "obsequious", "observant",
"observation", "observe", "obsolete", "obtain", "obtainable", "occur", "ocean",
"oceanic", "odd", "offbeat", "offend", "offer", "offer", "office", "oil", "old",
"old-fashioned", "omniscient", "one", "onerous", "open", "open", "opposite", "optimal",
"orange", "orange", "oranges", "order", "order", "ordinary", "organic", "ossified",
"outgoing", "outrageous", "outstanding", "oval", "oven", "overconfident", "overflow",
"overjoyed", "overrated", "overt", "overwrought", "owe", "own", "pack", "paddle", "page",
"pail", "painful", "painstaking", "paint", "pale", "paltry", "pan", "pancake", "panicky",
"panoramic", "paper", "parallel", "parcel", "parched", "park", "parsimonious", "part",
"part", "partner", "party", "pass", "passenger", "past", "paste", "pastoral", "pat",
"pathetic", "pause", "payment", "peace", "peaceful", "pear", "peck", "pedal", "peel",
"peep", "pen", "pencil", "penitent", "perfect", "perform", "periodic", "permissible",
"permit", "perpetual", "person", "pest", "pet", "petite", "petite", "pets", "phobic",
"phone", "physical", "picayune", "pick", "pickle", "picture", "pie", "pies", "pig",
"pigs", "pin", "pinch", "pine", "pink", "pipe", "piquant", "pizzas", "place", "place",
"placid", "plain", "plan", "plane", "planes", "plant", "plant", "plant", "plantation",
"plants", "plastic", "plastic", "plate", "plausible", "play", "play", "playground",
"pleasant", "please", "pleasure", "plot", "plough", "plucky", "plug", "pocket", "point",
"point", "pointless", "poised", "poison", "poke", "polish", "polite", "political",
"pray", "preach", "precede", "precious", "prefer", "premium", "prepare", "present",
"present", "preserve", "press", "pretend", "pretty", "prevent", "previous", "price",
"pricey", "prick", "prickly", "print", "private", "probable", "produce", "produce",
"productive", "profit", "profuse", "program", "promise", "property", "prose", "protect",
"question", "questionable", "queue", "quick", "quickest", "quicksand", "quiet", "quiet",
"quill", "quilt", "quince", "quirky", "quiver", "quixotic", "quizzical", "rabbit",
"rabbits", "rabid", "race", "racial", "radiate", "ragged", "rail", "railway", "rain",
"rain", "rainstorm", "rainy", "raise", "rake", "rambunctious", "rampant", "range",
"rapid", "rare", "raspy", "rat", "rate", "ratty", "ray", "reach", "reaction", "reading",
"ready", "real", "realise", "reason", "rebel", "receipt", "receive", "receptive",
"recess", "recognise", "recondite", "record", "record", "red", "reduce", "redundant",
"reflect", "reflective", "refuse", "regret", "regret", "regular", "reign", "reject",
"rejoice", "relation", "relax", "release", "relieved", "religion", "rely", "remain",
"remarkable", "remember", "remind", "reminiscent", "remove", "repair", "repeat",
"replace", "reply", "report", "representative", "reproduce", "repulsive", "request",
"request", "rescue", "resolute", "resonant", "respect", "responsible", "rest", "retire",
"return", "reward", "rhetorical", "rhyme", "rhythm", "rice", "rich", "riddle", "rifle",
"right", "righteous", "rightful", "rigid", "ring", "rings", "rinse", "ripe", "risk",
"ritzy", "river", "road", "roasted", "rob", "robin", "robust", "rock", "rock", "rod",
"roll", "roll", "romantic", "roof", "room", "roomy", "root", "rose", "rot", "rotten",
"rough", "round", "route", "royal", "rub", "rub", "ruddy", "rude", "ruin", "rule",
"rule", "run", "rural", "rush", "rustic", "ruthless", "sable", "sack", "sack", "sad",
"safe", "sail", "sail", "salt", "salty", "same", "sand", "sassy", "satisfy",
"satisfying", "save", "savory", "saw", "scale", "scandalous", "scarce", "scare",
"scarecrow", "scared", "scarf", "scary", "scatter", "scattered", "scene", "scent",
"school", "science", "scientific", "scintillating", "scissors", "scold", "scorch",
"scrape", "scratch", "scrawny", "scream", "screeching", "screw", "screw", "scribble",
"scrub", "sea", "seal", "search", "seashore", "seat", "second", "second-hand", "secret",
"secretary", "secretive", "sedate", "seed", "seemly", "selection", "selective", "self",
"selfish", "sense", "separate", "separate", "serious", "servant", "serve", "settle",
"shade", "shade", "shaggy", "shake", "shaky", "shallow", "shame", "shape", "share",
"sharp", "shave", "sheep", "sheet", "shelf", "shelter", "shiny", "ship", "shirt",
"shiver", "shivering", "shock", "shock", "shocking", "shoe", "shoes", "shop", "shop",
"short", "show", "shrill", "shrug", "shut", "shy", "sick", "side", "sidewalk", "sigh",
"sign", "sign", "signal", "silent", "silent", "silk", "silky", "silly", "silver",
"simple", "simplistic", "sin", "sincere", "sink", "sip", "sister", "sisters", "six",
"size", "skate", "ski", "skillful", "skin", "skinny", "skip", "skirt", "sky", "slap",
"slave", "sleep", "sleepy", "sleet", "slim", "slimy", "slip", "slip", "slippery",
"slope", "sloppy", "slow", "slow", "small", "smart", "smash", "smash", "smell", "smell",
"smelly", "smile", "smile", "smiling", "smoggy", "smoke", "smoke", "smooth", "snail",
"snails", "snake", "snakes", "snatch", "sneaky", "sneeze", "sneeze", "sniff", "snobbish",
"snore", "snotty", "snow", "snow", "soak", "soap", "society", "sock", "soda", "sofa",
"soft", "soggy", "solid", "somber", "son", "song", "songs", "soothe", "sophisticated",
"sordid", "sore", "sore", "sort", "sound", "sound", "soup", "sour", "space", "spade",
"spare", "spark", "spark", "sparkle", "sparkling", "special", "spectacular", "spell",
"spicy", "spiders", "spiffy", "spiky", "spill", "spiritual", "spiteful", "splendid",
"spoil", "sponge", "spooky", "spoon", "spot", "spot", "spotless", "spotted", "spotty",
"spray", "spring", "sprout", "spurious", "spy", "squalid", "square", "square", "squash",
"squeak", "squeal", "squealing", "squeamish", "squeeze", "squirrel", "stage", "stain",
"staking", "stale", "stamp", "stamp", "standing", "star", "stare", "start", "start",
"statement", "station", "statuesque", "stay", "steadfast", "steady", "steam", "steel",
"steep", "steer", "stem", "step", "step", "stereotyped", "stew", "stick", "sticks",
"sticky", "stiff", "stimulating", "stingy", "stir", "stitch", "stitch", "stocking",
"stomach", "stone", "stop", "stop", "store", "store", "stormy", "story", "stove",
"straight", "strange", "stranger", "strap", "straw", "stream", "street", "strengthen",
"stretch", "stretch", "string", "strip", "striped", "stroke", "strong", "structure",
"stuff", "stupendous", "stupid", "sturdy", "subdued", "subsequent", "substance",
"substantial", "subtract", "succeed", "successful", "succinct", "suck", "sudden",
"suffer", "sugar", "suggest", "suggestion", "suit", "suit", "sulky", "summer", "sun",
"super", "superb", "superficial", "supply", "support", "support", "suppose", "supreme",
"surprise", "surprise", "surround", "suspect", "suspend", "swanky", "sweater", "sweet",
"sweltering", "swift", "swim", "swing", "switch", "symptomatic", "synonymous", "system",
"table", "taboo", "tacit", "tacky", "tail", "talented", "talk", "talk", "tall", "tame",
"tame", "tan", "tangible", "tangy", "tank", "tap", "tart", "taste", "taste", "tasteful",
"tasteless", "tasty", "tawdry", "tax", "teaching", "team", "tearful", "tease", "tedious",
"teeny", "teeny-tiny", "teeth", "telephone", "telling", "temper", "temporary", "tempt",
"ten", "tendency", "tender", "tense", "tense", "tent", "tenuous", "terrible", "terrific",
"terrify", "territory", "test", "test", "tested", "testy", "texture", "thank",
"thankful", "thaw", "theory", "therapeutic", "thick", "thin", "thing", "things",
"thinkable", "third", "thirsty", "thirsty", "thought", "thoughtful", "thoughtless",
"thread", "threatening", "three", "thrill", "throat", "throne", "thumb", "thunder",
"thundering", "tick", "ticket", "tickle", "tidy", "tie", "tiger", "tight", "tightfisted",
"time", "time", "tin", "tiny", "tip", "tire", "tired", "tiresome", "title", "toad",
"toe", "toes", "tomatoes", "tongue", "tooth", "toothbrush", "toothpaste", "toothsome",
"top", "torpid", "touch", "touch", "tough", "tour", "tow", "towering", "town", "toy",
"toys", "trace", "trade", "trade", "trail", "train", "train", "trains", "tramp",
"tranquil", "transport", "transport", "trap", "trashy", "travel", "tray", "treat",
"treatment", "tree", "trees", "tremble", "tremendous", "trick", "trick", "tricky",
"trip", "trip", "trite", "trot", "trouble", "trouble", "troubled", "trousers", "truck",
"trucks", "truculent", "true", "trust", "truthful", "try", "tub", "tug", "tumble",
"turkey", "turn", "turn", "twig", "twist", "twist", "two", "type", "typical",
"ubiquitous", "ugliest", "ugly", "ultra", "umbrella", "unable", "unaccountable",
"unadvised", "unarmed", "unbecoming", "unbiased", "uncle", "uncovered", "understood",
"underwear", "undesirable", "undress", "unequal", "unequaled", "uneven", "unfasten",
"unhealthy", "uninterested", "unique", "unit", "unite", "unkempt", "unknown", "unlock",
"unnatural", "unpack", "unruly", "unsightly", "unsuitable", "untidy", "untidy", "unused",
"unusual", "unwieldy", "unwritten", "upbeat", "uppity", "upset", "uptight", "use", "use",
"used", "useful", "useless", "utopian", "utter", "uttermost", "vacation", "vacuous",
"vagabond", "vague", "valuable", "value", "van", "vanish", "various", "vase", "vast",
"vegetable", "veil", "vein", "vengeful", "venomous", "verdant", "verse", "versed",
"vessel", "vest", "victorious", "view", "vigorous", "violent", "violet", "visit",
"visitor", "vivacious", "voice", "voiceless", "volatile", "volcano", "volleyball",
"voracious", "voyage", "vulgar", "wacky", "waggish", "wail", "wait", "waiting",
"wakeful", "walk", "walk", "wall", "wander", "wandering", "want", "wanting", "war",
"warlike", "warm", "warm", "warn", "wary", "wash", "wash", "waste", "waste", "wasteful",
"watch", "watch", "water", "water", "watery", "wave", "wave", "waves", "wax", "way",
"weak", "wealth", "wealthy", "weary", "weather", "week", "weigh", "weight", "welcome",
"well-groomed", "well-made", "well-off", "well-to-do", "wet", "wheel", "whimsical",
"whine", "whip", "whip", "whirl", "whisper", "whispering", "whistle", "whistle", "white",
"whole", "wholesale", "wicked", "wide", "wide-eyed", "wiggly", "wild", "wilderness",
"willing", "wind", "window", "windy", "wine", "wing", "wink", "winter", "wipe", "wire",
"wiry", "wise", "wish", "wish", "wistful", "witty", "wobble", "woebegone", "woman",
"womanly", "women", "wonder", "wonderful", "wood", "wooden", "wool", "woozy", "word",
"work", "work", "workable", "worm", "worried", "worry", "worthless", "wound", "wrap",
"wrathful", "wreck", "wren", "wrench", "wrestle", "wretched", "wriggle", "wrist",
"writer", "writing", "wrong", "wry", "x-ray", "yak", "yam", "yard", "yarn", "yawn",
"year", "yell", "yellow", "yielding", "yoke", "young", "youthful", "yummy", "zany",
"zealous", "zebra", "zephyr", "zesty", "zinc", "zip", "zipper", "zippy", "zonked", "zoo",
"zoom" ];

let s:string = "";

let startTime:Date, endTime:Date, timeDiff:number;

let results:string[];

// console.log(words);


function buildArray( words:string[] ){
	let optimalArray:string[] = [];

	for ( let x = 0; x < words.length; x++ ) {
		const word = words[x];
		for ( let i = 1; i < word.length; i++ ) {
			// console.log(word.slice(0,i));
			if( undefined === optimalArray[word.slice(0,i)] ){
				optimalArray[word.slice(0,i)] = [];
			}
			optimalArray[word.slice(0,i)].push(word);
		}
	}
	return optimalArray;
}

let optimalWords:string[] = [];

optimalWords = buildArray( words );

function returnAutoComplete(s:string, words:string[]){
	let matches:string[] = [];

	matches = words.filter((word) => word.indexOf(s) === 0);

	return matches;
}

startTime = new Date();

s = "desc";

results = returnAutoComplete(s, words);

console.log( 'Possible Matches: ' + results);

endTime = new Date();
timeDiff = ( endTime.getTime() - startTime.getTime() ); //in ms

console.log("Time elasped " + timeDiff + " seconds with non-optimized array");

startTime = new Date();

console.log( 'Possible Matches: ' + optimalWords[s]);

endTime = new Date();
timeDiff = ( endTime.getTime() - startTime.getTime() ); //in ms

console.log("Time elasped " + timeDiff + " seconds with optmized array");
